import React from "react";
import Head from "next/head";
import Image from "next/image";
import Footer from "../components/common/Footer";
import Navbar from "../components/common/Navbar";
import {
  Stack,
  Heading,
  Container,
  Box,
  Text,
  SimpleGrid,
  Button,
  Center,
  List,
  ListIcon,
  ListItem,
  VStack,
  useBreakpointValue,
} from "@chakra-ui/react";
import { FaCheckCircle } from "react-icons/fa";
import CryptoChartTape from "../components/common/CryptoChartTape";
import { mining_place } from "../assets/images/list";

function Privacy() {
  return (
    <Box>
      <Head>
        <title>Terms & Conditions - Bitcloud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Box
        w="full"
        h={{ base: "xs", md: "xs" }}
        // bg="blue.400"
        id="contact"
        // bgGradient={"linear(to-r, blackAlpha.600, transparent)"}
      >
        <VStack
          w={"full"}
          h="full"
          justify={"center"}
          px={useBreakpointValue({ base: 4, md: 8 })}
          bgGradient={"linear(to-r, blackAlpha.600, blackAlpha.600)"}
        >
          <Center w="inherit" h="inherit">
            <Box maxW="3xl" textAlign="left" px={{ base: 12, md: 0 }}>
              <Heading
                // fontWeight={600}
                fontSize={{ base: "2xl", sm: "4xl", md: "6xl" }}
                lineHeight={"110%"}
                color="white"
              >
                <Text>Terms & Conditions</Text>
              </Heading>
            </Box>
          </Center>
        </VStack>
      </Box>

      <Container maxW={"6xl"} my={10}>
        <Box>
          <Stack as={Container} maxW={"6xl"} mt={10}>
            <Heading
              lineHeight={"110%"}
              fontSize={{ base: "2xl", sm: "4xl", md: "4xl" }}
              fontWeight="bold"
              mb={3}
            >
              <Text>Terms and Conditions</Text>
            </Heading>
            <Text my={10}>
              Welcome to Bitcloud These terms and conditions outline the rules
              and regulations for the use of bit-cloudminer.co's Website,
              located at https://bitcloud.network. By accessing this website we
              assume you accept these terms and conditions. Do not continue to
              use bit-cloudminer.co if you do not agree to take all of the terms
              and conditions stated on this page.
            </Text>
            <Text mt={30}>
              The following terminology applies to these Terms and Conditions,
              Privacy Statement and Disclaimer Notice and all Agreements:
              "Client", "You" and "Your" refers to you, the person log on this
              website and compliant to the Company’s terms and conditions. "The
              Company", "Ourselves", "We", "Our" and "Us", refers to our
              Company. "Party", "Parties", or "Us", refers to both the Client
              and ourselves. All terms refer to the offer, acceptance and
              consideration of payment necessary to undertake the process of our
              assistance to the Client in the most appropriate manner for the
              express purpose of meeting the Client’s needs in respect of
              provision of the Company’s stated services, in accordance with and
              subject to, prevailing law of Netherlands. Any use of the above
              terminology or other words in the singular, plural, capitalization
              and/or he/she or they, are taken as interchangeable and therefore
              as referring to same.
            </Text>
          </Stack>

          <Heading
            lineHeight={"110%"}
            fontSize={{ base: "xl", sm: "xl", md: "xl" }}
            fontWeight="bold"
            // mb={3}
            mt={10}
            p={4}
          >
            <Text>Cookies</Text>
          </Heading>
          <Text p={4}>
            We employ the use of cookies. By accessing Bitcloud, you agreed to
            use cookies in agreement with the Bitcloud's Privacy Policy. Most
            interactive websites use cookies to let us retrieve the user’s
            details for each visit. Cookies are used by our website to enable
            the functionality of certain areas to make it easier for people
            visiting our website. Some of our affiliate/advertising partners may
            also use cookies.
          </Text>

          <Heading
            lineHeight={"110%"}
            fontSize={{ base: "xl", sm: "xl", md: "xl" }}
            fontWeight="bold"
            // mb={3}
            mt={10}
            p={4}
          >
            <Text>License</Text>
          </Heading>
          <Text p={4}>
            Unless otherwise stated, Bitcloud and/or its licensors own the
            intellectual property rights for all material on Bitcloud. All
            intellectual property rights are reserved. You may access this from
            Bitcloud for your own personal use subjected to restrictions set in
            these terms and conditions.
          </Text>
          <Text p={4}>
            You must not:
          </Text>
          <List spacing={3} textAlign="start" p={4}>
            <ListItem>
              <ListIcon as={FaCheckCircle} color="yellow.500" />
              Republish material from Bitcloud
            </ListItem>
            <ListItem>
              <ListIcon as={FaCheckCircle} color="yellow.500" />
              Sell, rent or sub-license material from Bitcloud
            </ListItem>

            <ListItem>
              <ListIcon as={FaCheckCircle} color="yellow.500" />
              Reproduce, duplicate or copy material from Bitcloud
            </ListItem>

            <ListItem>
              <ListIcon as={FaCheckCircle} color="yellow.500" />
              Redistribute content from Bitcloud
            </ListItem>
          </List>
        </Box>
      </Container>

      <CryptoChartTape />
      <Footer />
    </Box>
  );
}

export default Privacy;
